### ISSUE TITLE
No Ninjas Error

### ISSUE THREAD

**Issue by mananpasrija123** [ErAz7/Jonin#1]
It is showing no ninjas , i have installed it on the victim also , but it's showing no nijas, double checked the ports and host
Pls help

**Comment by ErAz7** [comment]
is the port forwarded on Jonin (controller) side?

**Comment by mananpasrija123** [comment]
How to do it ?

**Comment by mananpasrija123** [comment]
how do i port foward it

**Comment by ErAz7** [comment]
Please check [Setup](https://github.com/ErAz7/Jonin#setup) and [Fix No Ninjas Error](https://github.com/ErAz7/Jonin#fix-no-ninjas-error) sections if you're getting `No Ninjas`

**Comment by ErAz7** [comment]
@mananpasrija123 could you resolve the issue?

**Comment by ErAz7** [comment]
feel free to reopen if the solution didn't work
